#!/usr/bin/env bash

# This file contains a manifest of all the config linkages that are served by dotfiles. The links associate a local repo path with a full filesystem path.
# The link format is [<local repo path>]="<full filesystem path>"

declare -A links
links=(
  ['./efm-langserver']="$HOME/.config/efm-langserver"
  ['./nvim']="$HOME/.config/nvim"
  ['./zsh']="$HOME/.zsh"
  ['./zsh/zshrc']="$HOME/.zsh/.zshrc"
  ['./zsh/zshenv']="$HOME/.zshenv"
  ['./kitty']="$HOME/.config/kitty"
  ['./tmux/tmux.conf']="$HOME/.tmux.conf"
  ['./karabiner']="$HOME/.config/karabiner"
  ['./bin']="$HOME/bin"
)
