#!/usr/bin/env bash

# This file unlinks all links in the manifest
source ./link-manifest

declare -A inverted_links
for key in "${!links[@]}"; do
  value="${links[$key]}"
  inverted_links["$value"]="$key"
done

declare -a __depths
__depths=()
for target in ${links[@]}; do
  count=$(tr -dc '/' <<< "$target" | wc -c)
  __depths+=("$count/$target")
done

__targets_by_depth_base=$(echo "${__depths[@]}" | tr ' ' '\n' | tr -s '\n' '\n' | sort -t/ -k1 | cut -d '/' -f 2-)
__targets_by_depth=$(echo "$__targets_by_depth_base" | sort)
__targets_by_depth_reverse=$(echo "$__targets_by_depth_base" | sort -r)

declare -a link_sources_by_target_depths
link_sources_by_target_depths=()
for target in $__targets_by_depth; do
  repo_source="${inverted_links[$target]}"
  link_sources_by_target_depths+=("${repo_source}")
done

declare -a link_sources_by_target_depths_reverse
link_sources_by_target_depths_reverse=()
for target in $__targets_by_depth_reverse; do
  repo_source="${inverted_links[$target]}"
  link_sources_by_target_depths_reverse+=("${repo_source}")
done

usage() {
  echo "Usage: dotfiles <command>"
  echo "Commands:"
  echo "  link -- link dotfiles to the local system"
  echo "  unlink -- remove all links dotfiles from the local system"
  echo "  force-remove <dir> -- mova all files in the link paths to the specified directory"
  exit 1
}

if [ "$1" = 'link' ]; then
  for source in ${link_sources_by_target_depths[@]}; do
    target="${links[$source]}"
    echo "linking ${source} to ${target}"
    SOURCE_PATH=$(realpath ${source})
    echo "  ln -s ${SOURCE_PATH} ${links[$source]}"
    echo ""
    ln -s ${SOURCE_PATH} ${links[$source]}
  done
  exit 0
fi

if [ "$1" = 'unlink' ]; then
  for source in ${link_sources_by_target_depths_reverse[@]}; do
    echo "unlink ${links[$source]}"
    unlink ${links[$source]}
  done
  exit 0
fi

if [ "$1" = 'force-remove' ] && [ -n "$2" ]; then
  mkdir -p "$2"
  for source in ${link_sources_by_target_depths_reverse[@]}; do
    echo "mv ${links[$source]} $2"
    mv "${links[$source]}" "$2"
  done
  exit 0
fi


usage

